name: depthsplat
channels:
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.12.31=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2024.12.14=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.6=3
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=6.1.1=he32514a_1
  - filelock=3.13.1=py310h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - h5py=3.12.1=py310h5842655_1
  - harfbuzz=4.3.0=hf52aaf7_2
  - hdf5=1.14.5=h2b7332f_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py310h06a4308_1
  - jpeg=9e=h5eee18b_3
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.82.0=h42c8aad_2
  - lerc=3.0=h295c915_0
  - libarchive=3.7.7=hfab0078_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcurl=8.11.1=hc9e6f67_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtheora=1.1.1=h7f8727e_3
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.13.5=hfdd30dd_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py310h06a4308_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - numpy=2.0.1=py310h5f9d8c6_1
  - numpy-base=2.0.1=py310hb5e798b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - pip=24.2=py310h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.15=he870216_1
  - pytorch=2.4.0=py3.10_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_1
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.2=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tesseract=5.2.0=h6a678d5_2
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.4.0=py310_cu118
  - torchtriton=3.0.0=py310
  - torchvision=0.19.0=py310_cu118
  - typing_extensions=4.11.0=py310h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - urllib3=2.2.3=py310h06a4308_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.9
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - attrs==24.2.0
      - beartype==0.19.0
      - black==24.10.0
      - click==8.1.7
      - colorama==0.4.6
      - colorspacious==1.1.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - dacite==1.8.1
      - decorator==5.1.1
      - diff-gaussian-rasterization==0.0.0
      - docker-pycreds==0.4.0
      - e3nn==0.5.4
      - einops==0.8.0
      - fonttools==4.55.2
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - hydra-core==1.3.2
      - imageio==2.36.1
      - imageio-ffmpeg==0.5.1
      - jaxtyping==0.2.36
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightning-utilities==0.11.9
      - lpips==0.1.4
      - matplotlib==3.9.3
      - moviepy==2.1.1
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - packaging==24.2
      - pathspec==0.12.1
      - pillow==10.4.0
      - platformdirs==4.3.6
      - plyfile==1.1
      - proglog==0.1.10
      - propcache==0.2.1
      - protobuf==5.29.1
      - psutil==6.1.0
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytorch-lightning==2.4.0
      - ruff==0.8.2
      - scikit-image==0.24.0
      - scipy==1.14.1
      - sentry-sdk==2.19.1
      - setproctitle==1.3.4
      - six==1.17.0
      - sk-video==1.1.10
      - smmap==5.0.1
      - svg-py==1.5.0
      - tabulate==0.9.0
      - tifffile==2024.9.20
      - tomli==2.2.1
      - torchmetrics==1.6.0
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - wandb==0.19.1
      - xformers==0.0.29+5a9fc9b.d20241206
      - yarl==1.18.3
prefix: /root/miniconda3/envs/depthsplat
